Ruby216_32/lib/ruby/gems/2.1.0/gems/smalruby-editor-0.4.0-x86-mingw32/config/routes.rb
# -*- coding: utf-8 -*-
SmalrubyEditor::Application.routes.draw do
  scope '(:locale)', locale: /en|ja/ do
    root to: 'editor#index'
  end

  match '/demo(/:filename)' => 'editor#demo',
        defaults: { filename: 'car_chase' }, via: :get

  resources :sessions, only: [:create, :destroy]
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :users, only: [:update]
  resources :costumes, only: [:index, :create, :destroy]
  get "/smalruby/assets/:basename", to: "costumes#show"

  resources :source_codes, only: [:create, :index]
  post 'source_codes/check'
  delete 'source_codes/download'
  post 'source_codes/load'
  post 'source_codes/load_local'
  post 'source_codes/load_demo'
  delete 'source_codes/write'
  post 'source_codes/run'
  post 'source_codes/to_blocks'

  get 'preferences', to: 'users#preferences'
  get 'toolbox', to: 'editor#toolbox'
end

Ruby216_32/lib/ruby/gems/2.1.0/gems/smalruby-editor-0.4.0-x86-mingw32/app/controllers/editor_controller.rb
# -*- coding: utf-8 -*-
require "ostruct"

class EditorController < ApplicationController
  def index
  end

  def demo
    @filename = (File.basename(params[:filename]) || 'car_chase') + '.rb.xml'
  end

  def toolbox
    render :toolbox, layout: false
  end
end

Ruby216_32/lib/ruby/gems/2.1.0/gems/smalruby-editor-0.4.0-x86-mingw32/app/helpers/editor_helper.rb
# -*- coding: utf-8 -*-
module EditorHelper
  # ツールボックスのブロックに対して、キャラクターの入力フィールドの値を設定する
  #
  # @param [String] name 名前
  # @return [String] XML
  def toolbox_character_field(name = 'VAR')
    %(<field name="#{h name}">char1</field>).html_safe
  end

  # ツールボックスのブロックに対して、キーの入力フィールドの値を設定する
  #
  # @param [String] name 名前
  # @param [String] value キーの名前。K_SPACE、K_Aなど
  # @return [String] XML
  def toolbox_key_field(name = 'KEY', value = 'K_SPACE')
    %(<field name="#{h name}">#{h value}</field>).html_safe
  end

  # push or down field for Toolbox
  #
  # @param [String] name field name
  # @param [String] value :push or :down
  # @return [String] XML
  def toolbox_pod_field(name = 'POD', value = :down)
    if value == :down
      pod = 'down'
    else
      pod = 'push'
    end
    %(<field name="#{h name}">#{pod}</field>).html_safe
  end

  # ツールボックスのブロックに対して、PINの入力フィールドの値を設定する
  #
  # @param [String] value ピン
  # @param [String] name 名前
  # @return [String] XML
  def toolbox_pin_field(value, name = 'PIN')
    %(<field name="#{h name}">#{h value}</field>).html_safe
  end

  # ツールボックスのブロックに対して、数値型の入力のブロックを設定する
  #
  # @param [String] name 入力値の名前
  # @param [Numeric] value 数値
  # @return [String] XML
  def toolbox_number_value(name, value = 0)
    value = value.to_i unless value.is_a?(Numeric)
    <<-XML.strip_heredoc.html_safe
      <value name="#{h name}">
        <block type="math_number">
          <field name="NUM">#{h value}</field>
        </block>
      </value>
    XML
  end

  # ツールボックスのブロックに対して、テキスト型の入力のブロックを設定する
  #
  # @param [String] name 入力値の名前
  # @param [String] value 文字列
  # @return [String] XML
  def toolbox_text_value(name = 'TEXT', value = '')
    <<-XML.strip_heredoc.html_safe
      <value name="#{h name}">
        <block type="text">
          <field name="TEXT">#{h value}</field>
        </block>
      </value>
    XML
  end

  # I18n.t wrapper for Toolbox that's defualt scope is
  # 'editor.toolbox'.
  def toolbox_t(*args)
    if args.length == 1 && args.first[0] == '.'
      t(args.first[1..-1], scope: 'editor.toolbox')
    else
      t(*args)
    end
  end
  alias_method :tt, :toolbox_t
end

Ruby216_32/lib/ruby/gems/2.1.0/gems/smalruby-editor-0.4.0-x86-mingw32/app/views/editor/_block_tab.html.haml
#block-tab-right-pane{:class => 'right-pane'}
  #blockly-div

  = render "toolbox_#{toolbox_name}"

#block-tab-left-pane{:class => 'left-pane'}
  #selectors-container
    %ul.nav{:class => 'nav-pills'}
      %li.active
        %a{:href => '#character-selector-tab', :'data-toggle' => 'tab'}<
          = t('.character')
      -#%li
        -#%a{:href => '#scene-selector-tab', :'data-toggle' => 'tab'}<
          -#= t('.stage')

    #selectors-tab-content{:class => 'tab-content'}
      #character-selector-tab{:class => 'tab-pane active selector-tab'}
        #character-selector-character-set
        #add-character-item.item
          %a#add-character-button{:class => 'character'}
            %i.icon-plus-sign-alt
            %br
            = t('.new_character')

      #scene-selector-tab{:class => 'tab-pane selector-tab'}
        .item
          %a{:href => '#', :onclick => 'window.event.preventDefault();'}
            %div
        .item
          %a{:href => '#', :onclick => 'window.event.preventDefault();'}
            %div

= render 'character_modal'

%script#character-selector-template{:type => 'text/template'}
  .item
    .item-info
      .name
        {{- get('name') }}
      .attributes
        X: {{- get('x') }} Y: {{- get('y') }}
        %br
        = t('.direction_parameter')
        %i{class: "{{- rotationStyleIconName() }}"}
        {{- get('angle') }}°

      %a.add-block-button
        %i.icon-folder-close-alt
        %i.icon-double-angle-right

      %a.remove-button
        %i.icon-remove

    %a.character
      %img{:src => '{{- costumeUrl() }}'}

Ruby216_32/lib/ruby/gems/2.1.0/gems/smalruby-editor-0.4.0-x86-mingw32/app/views/editor/_character_modal.html.haml
#character-modal{:class => "#{modal_css_class}", :tabindex => '-1',
                 :role => 'dialog', :'aria-hidden' => 'true'}
  .modal-body
    #character-modal-right-pane{:class => 'right-pane'}
      #character-modal-right-pane-inner
        #character-modal-right-pane-inner-right-pane{:class => 'right-pane'}
          %form#character-modal-costume-form{:class => 'form-horizontal'}
            .control-group{for: "costume[name]"}
              %label.control-label{for: "costume_name"}<
                = t('.costume_name')
              .controls
                %input#costume_name.input-large{name: "costume[name]", type: "text", placeholder: t('.msg_input_costume_name')}

          #character-modal-costume-selector

        #character-modal-right-pane-inner-left-pane{:class => 'left-pane'}
          #character-modal-costume-set-header
            = t('.costumes')
          #character-modal-costume-set-container
            #character-modal-costume-set
            #character-modal-add-costume.item
              %a#character-modal-add-costume-button.costume
                %i.icon-plus-sign-alt
                %br
                = t('.new_costume')

    #character-modal-left-pane{:class => 'left-pane'}
      #character-modal-preview
        #character-modal-character
          %img{:src => "/smalruby/assets/car1.png"}

      #character-modal-attributes
        %form#character-modal-form{:class => 'form-horizontal'}
          .control-group{:for => "character[name]"}
            %label.control-label{:for => 'character_name'}<
              = t('.name')
            .controls
              %input#character_name{:name => 'character[name]', :type => 'text', :placeholder => t('.msg_input_name'), :class => 'input-large'}
          .control-group
            %label.control-label{:for => 'character_x'}<
              = t('.x_position')
            .controls
              %input#character_x{:name => 'character[x]', :type => 'range', :min => '0', :max => '639', :class => 'input-large'}
              %span#character_x_value{:class => 'character_value'}
                300
          .control-group
            %label.control-label{:for => 'character_y'}<
              = t('.y_position')
            .controls
              %input#character_y{:name => 'character[y]', :type => 'range', :min => '0', :max => '439', :class => 'input-large'}
              %span#character_y_value{:class => 'character_value'}
                200
          .control-group
            %label.control-label{:for => 'character_angle'}<
              = t('.direction')
            .controls
              #character_rotation_style.btn-group
                %button#character_rotation_style_free.btn{type: "button", class: "btn-small", value: "free"}<
                  %i.icon-repeat
                %button#character_rotation_style_left_right.btn{type: "button", class: "btn-small", value: "left_right"}<
                  %i.icon-resize-horizontal
                %button#character_rotation_style_none.btn{type: "button", class: "btn-small", value: "none"}<
                  %i.icon-arrow-right
              %input#character_angle{:name => 'character[angle]', :type => 'range', :min => '0', :max => '359', :class => 'input-small', style: "margin-left: 4px;"}
              %span#character_angle_vector{:class => 'character_value'}
                →
              %span#character_angle_value{:class => 'character_value', style: "margin-left: 4px;"}
                100°

  .modal-footer
    %button.btn{:'data-dismiss' => 'modal', :'aria-hidden' => 'true'}<
      %i.icon-remove
      = t('common.cancel')
    %button#character-modal-ok-button{:class => 'btn btn-primary'}<
      %i.icon-circle-blank
      = t('common.ok')

%script#character-modal-costume-template{:type => 'text/template'}
  .item
    .item-info
      .name
        {{- name }}
      .attributes
        {{- index }}

      %a.remove-button
        %i.icon-remove

    %a.costume
      %img{src: '{{- path }}', alt: '{{- basename }}'}

Ruby216_32/lib/ruby/gems/2.1.0/gems/smalruby-editor-0.4.0-x86-mingw32/app/views/editor/_load_modal.html.haml
#load-modal{:class => "#{modal_css_class}", :tabindex => "-1",
            :role => "dialog", :"aria-hidden" => "true"}
  .modal-body
    %ul.thumbnails{:id => "load-modal-local-programs",
                   :class => "list-programs"}

    .page-header
      %h3
        %i.icon-th-large
        = t('.preset_programs')
    %ul.thumbnails{:id => "load-modal-demo-programs",
                   :class => "list-programs"}

    .page-header
      %h3
        %i.icon-search
        = t('.find_program')
    %ul.thumbnails{:class => "list-programs"}
      %li
        %a#load-modal-find-from-computer.thumbnail
          %h1.icon
            %i.icon-folder-open-alt
          %blockquote
            %p
              = t('.computer')
            %small
              Computer

  .modal-footer
    .pull-left
      %button#load-modal-remix-button.btn<
        %i.icon-refresh
        = t('.remix')
    %button.btn{:"data-dismiss" => "modal", :"aria-hidden" => "true"}<
      %i.icon-remove
      = t('common.cancel')
    %button#load-modal-ok-button{:class => "btn btn-primary"}<
      %i.icon-circle-blank
      = t('common.ok')

Ruby216_32/lib/ruby/gems/2.1.0/gems/smalruby-editor-0.4.0-x86-mingw32/app/views/editor/_preference_modal.html.haml
#preference-modal{class: "#{modal_css_class}", tabindex: "-1",
                  role: "dialog", "aria-hidden" => "true"}
  .modal-header
    %h3
      %i.icon-cog
      = t('.title')

  .modal-body#preference-modal-content

  .modal-footer
    %button.btn{:"data-dismiss" => "modal", :"aria-hidden" => "true"}<
      %i.icon-remove
      = t('common.cancel')
    %button#preference-modal-ok-button{:class => "btn btn-primary"}<
      %i.icon-circle-blank
      = t('common.ok')

Ruby216_32/lib/ruby/gems/2.1.0/gems/smalruby-editor-0.4.0-x86-mingw32/app/views/editor/_reset_modal.html.haml
#reset-modal{class: "#{modal_css_class}", tabindex: "-1",
             role: "dialog", :"aria-hidden" => "true"}
  .modal-header
    %h3
      = t('.title')
  .modal-body
    %p
      = t('.message')
  .modal-footer
    %button#reset-modal-cancel-button.btn{:"data-dismiss" => "modal", :"aria-hidden" => "true"}<
      %i.icon-remove
      = t('common.cancel')
    %button#reset-modal-ok-button.btn{class: "btn-primary"}<
      %i.icon-off
      = t('common.reset')

Ruby216_32/lib/ruby/gems/2.1.0/gems/smalruby-editor-0.4.0-x86-mingw32/app/views/editor/_signin_modal.html.haml
#signin-modal{class: "#{modal_css_class}", tabindex: "-1",
              role: "dialog", :"aria-hidden" => "true"}
  .modal-body
    %h4
      %i.icon-info-sign
      = raw(t('.message'))
    %form#signin-modal-form.form-horizontal
      .control-group{for: "username"}
        %label.control-label{for: "signin-modal-username"}<
          = t('common.name')
        .controls
          %input#signin-modal-username.input-large{name: "username", type: "text", placeholder: t('.username_placeholder')}

  .modal-footer
    %button#signin-modal-cancel-button.cancel-button{class: "btn", :"data-dismiss" => "modal", :"aria-hidden" => "true"}<
      %i.icon-remove
      = t('common.cancel')
    %button#signin-modal-ok-button.ok-button{class: "btn btn-primary"}<
      %i.icon-circle-blank
      = t('common.login')

Ruby216_32/lib/ruby/gems/2.1.0/gems/smalruby-editor-0.4.0-x86-mingw32/app/views/editor/_toolbox_smalrubot.html.haml
-# @params type [String] s1, v3 and etc...
- subcategory = "smalrubot_#{type}"
%xml{:id => 'toolbox', :style => 'display: none'}
  %category{:name => tt('.motion')}
    - category = 'hardware'
    %block{type: "#{category}_#{subcategory}_action"}
      %field{name: 'ACTION'}<
        forward

    %block{type: "#{category}_#{subcategory}_action_with_sec"}
      %field{name: 'ACTION'}<
        forward
      = toolbox_number_value('SEC', 0.5)

    %block{type: "#{category}_#{subcategory}_dc_motor_set_power_ratio"}
      = toolbox_number_value('SPEED', 100)

  - category = 'looks'
  %category{:name => tt('.looks')}
    %block{:type => "#{category}_say"}
      %value{name: 'TEXT'}
        - category = 'hardware'
        %block{type: "#{category}_#{subcategory}_sensor_value"}

    - category = 'hardware'
    %block{type: "#{category}_#{subcategory}_led_turn_on_or_off"}
      %field{name: 'OOO'}<
        turn_on

  - category = 'sound'
  %category{:name => tt('.sound')}

  - category = 'pen'
  %category{:name => tt('.pen')}

  %category{:name => tt('.data'), :custom => 'VARIABLE'}

  - category = 'events'
  %category{:name => tt('.events')}
    -# まずは
    %block{:type => "#{category}_on_start"}

    -# キーボードの[▼キー]が[▼押された/押され続けている]とき
    %block{:type => "#{category}_on_key_push_or_down"}
      = toolbox_key_field
      = toolbox_pod_field

    -# キャラクターがクリックされたとき
    %block{:type => "#{category}_on_click"}

  - category = 'control'
  %category{:name => tt('.control')}
    -# (　)秒待つ
    %block{:type => "#{category}_sleep"}
      = toolbox_number_value('SEC', 1)

    -# ほんの少し待つ
    %block{:type => "#{category}_await"}

    -# (　)回繰り返す
    %block{:type => "#{category}_times"}
      = toolbox_number_value('COUNT', 10)

    -# ずっと
    %block{:type => "#{category}_loop"}

    -# もし<　>なら
    %block{:type => "#{category}_if"}

    -# もし<　>なら～でなければ
    %block{:type => "#{category}_if_else"}

    -# <　>まで待つ
    %block{:type => "#{category}_await_until"}

    -# <　>まで繰り返す
    %block{:type => "#{category}_until"}

    -# 繰り返しから脱出する
    %block{:type => "#{category}_break"}

    -# 次の繰り返しにジャンプする
    %block{:type => "#{category}_next"}

  - category = 'sensing'
  %category{:name => tt('.sensing')}
    -# 条件:キーボードの[▼キー]が[▼押された]
    %block{:type => "#{category}_input_key_push_or_down"}
      = toolbox_key_field
      = toolbox_pod_field

    -# 条件:マウスの[▼左ボタン]が[▼押された]
    %block{:type => "#{category}_input_mouse_push_or_down"}
      = toolbox_pod_field

    -# [　]と聞いて待つ
    -#%block{:type => "#{category}_ask"}
    -#  = toolbox_text_value('TEXT', 'あなたのお名前は？')

    -# 変数:答え
    -#%block{:type => "#{category}_answer"}

    -# 変数:タイマー
    -#%block{:type => "#{category}_timer_count"}

    -# タイマーをリセット
    -#%block{:type => "#{category}_timer_reset"}

    - category = 'hardware'
    %block{type: "#{category}_#{subcategory}_sensor_value"}
    %block{type: "#{category}_#{subcategory}_dc_motor_power_ratio"}

  - category = 'operators'
  %category{:name => tt('.operators')}
    -# 数値
    %block{:type => 'math_number'}
      %field{:name => 'NUM'}<
        0

    -# テキスト
    %block{:type => 'text'}
      %field{:name => 'TEXT'}<
        = tt('.text')

    -# 変数:(　) + (　)
    %block{:type => "#{category}_add"}

    -# 変数:(　) - (　)
    %block{:type => "#{category}_minus"}

    -# 変数:(　) * (　)
    %block{:type => "#{category}_multiply"}

    -# 変数:(　) / (　)
    %block{:type => "#{category}_divide"}

    -# 変数:(　)から(　)までの乱数
    %block{:type => "#{category}_rand"}
      = toolbox_number_value('A', 1)
      = toolbox_number_value('B', 10)

    -# 条件:(　) < (　)
    %block{:type => "#{category}_compare_lt"}

    -# 条件:(　) <= (　)
    %block{:type => "#{category}_compare_lte"}

    -# 条件:(　) = (　)
    %block{:type => "#{category}_compare_eq"}

    -# 条件:(　) >= (　)
    %block{:type => "#{category}_compare_gte"}

    -# 条件:(　) > (　)
    %block{:type => "#{category}_compare_gt"}

    -# 条件:<　> かつ <　>
    %block{:type => "#{category}_and"}

    -# 条件:<　> または <　>
    %block{:type => "#{category}_or"}

    -# 条件:<　> ではない
    %block{:type => "#{category}_negate"}

    -# 変数:(　)の(　)番目
    %block{:type => "#{category}_index_of"}
      = toolbox_text_value('A', tt('.world'))
      = toolbox_number_value('INDEX', 1)

    -# 変数:(　)の長さ
    %block{:type => "#{category}_length"}
      = toolbox_text_value('A', tt('.world'))

    -# 変数:(　)を(　)で割った余り
    %block{:type => "#{category}_modulo"}
      = toolbox_number_value('A', 5)
      = toolbox_number_value('B', 2)

    -# 変数:(　)を四捨五入
    %block{:type => "#{category}_round"}
      = toolbox_number_value('A', 0.5)

    -# 変数:(　)の[▼数学関数]
    %block{:type => "#{category}_math_method"}
      = toolbox_number_value('NUM', 9)
      %field{:name => 'METHOD'}<
        Math.sqrt(%num%)

    -# 条件:真
    %block{:type => "#{category}_true"}

    -# 条件:偽
    %block{:type => "#{category}_false"}

  %category{:name => tt('.etc')}

Ruby216_32/lib/ruby/gems/2.1.0/gems/smalruby-editor-0.4.0-x86-mingw32/app/views/editor/_toolbox_smalrubot_s1.html.haml
= render(partial: "toolbox_smalrubot", locals: { type: "s1" })

Ruby216_32/lib/ruby/gems/2.1.0/gems/smalruby-editor-0.4.0-x86-mingw32/app/views/editor/_toolbox_smalrubot_v3.html.haml
= render(partial: "toolbox_smalrubot", locals: { type: "v3" })

Ruby216_32/lib/ruby/gems/2.1.0/gems/smalruby-editor-0.4.0-x86-mingw32/app/views/editor/demo.html.erb
<%= render template: 'editor/index' %>

<script type="text/javascript">
  $(function() {
    var data = '<%= escape_javascript(File.read(Rails.root.join("demos/#{@filename}"))) %>';
    data = $('<div>').html(data).text();
    Smalruby.loadXml(data);

    var filename = $('<div>').html('<%= escape_javascript(@filename.sub(/\.rb\.xml$/, '.rb')) %>').text();
    $('#filename').val(filename)

    window.changed = false;
  });
</script>

Ruby216_32/lib/ruby/gems/2.1.0/gems/smalruby-editor-0.4.0-x86-mingw32/app/views/editor/index.html.haml
.navbar{:id => "main-menu", :class => 'navbar-inverse'}
  .navbar-inner
    %ul.nav{:id => 'tabs'}
      %li.active
        %a#block-mode-button{:href => "#block-tab"}<
          %i.icon-folder-close
          =t('.block')
      %li
        %a#ruby-mode-button{:href => "#ruby-tab"}<
          %i.icon-pencil
          Ruby

    = form_tag(source_codes_load_path, id: "file-form", class: "navbar-form pull-right", method: "post", multipart: true) do
      %input#load-file{:type => 'file', :name => 'source_code[file]', :style => 'display: none'}
      %input#filename{:type => 'text', :class => 'span4', :placeholder => t('.msg_input_program_name')}
      = link_to '', source_codes_download_path, id: 'download-link', style: 'display: none', 'data-method' => 'delete'

      - if standalone?
        %button#run-button{:class => "btn btn-success"}<
          %i.icon-flag
          = t('.run')
      - else
        %button#download-button{:class => "btn btn-primary"}<
          %i.icon-download-alt
          = t('.download')

      - if raspberrypi?
        - if standalone?
          - load_id = 'load-local-button'
        - else
          - load_id = 'load-button'
        %button.btn{id: "#{load_id}", class: "btn btn-primary"}<
          %i.icon-folder-open
          = t('.load')
        - if standalone?
          %button#save-button.btn{class: "btn-primary"}<
            %i.icon-hdd
            = t('.save')
        %button#check-button.btn{class: "btn-primary"}<
          %i.icon-check
          = t('.check')
        %button#reset-button.btn{class: "btn-primary"}<
          %i.icon-off
          = t('.reset')
        - if standalone?
          %button#signout-button.btn{class: "btn-primary", style: "display: #{signed_in? ? '' : 'none'}"}<
            %i.icon-eject
            = t('.logout')

      - else
        .btn-group
          %a#submenu-button{:class => "dropdown-toggle btn btn-primary", :"data-toggle" => "dropdown", :href => "#"}
            %i.icon-reorder
            = t('.menu')
          %ul#submenu.dropdown-menu{:class => "pull-right"}
            %li
              - if standalone?
                - load_id = 'load-local-button'
              - else
                - load_id = 'load-button'
              %a{:id => "#{load_id}"}
                %h4
                  %i.icon-folder-open
                  = t('.load')
            - if standalone?
              %li
                %a#save-button
                  %h4
                    %i.icon-hdd
                    = t('.save')
            %li
              %a#check-button
                %h4
                  %i.icon-check
                  = t('.check')
            %li
              %a#reset-button
                %h4
                  %i.icon-off
                  = t('.reset')
            - if standalone?
              %li.divider.signed-in-menu{style: "display: #{signed_in? ? '' : 'none'}"}
              %li
                %a#preference-button.signed-in-menu{style: "display: #{signed_in? ? '' : 'none'}"}
                  %h4
                    %i.icon-cog
                    = t('.preference')
              %li.divider.signed-in-menu{style: "display: #{signed_in? ? '' : 'none'}"}
              %li
                %a#signout-button.signed-in-menu{style: "display: #{signed_in? ? '' : 'none'}"}
                  %h4
                    %i.icon-eject
                    = t('.logout')

      - if standalone?
        - if session[:username]
          %button#signin-button{class: "btn btn-danger", style: "display: none"}<
            %i.icon-user
            = t('.login')
          %button#username-button{class: "btn btn-success"}<
            %i.icon-user
            %span#username-label<
              = session[:username]
        - else
          %button#signin-button{class: "btn btn-danger"}<
            %i.icon-user
            = t('.login')
          %button#username-button{class: "btn btn-success", style: "display: none"}<
            %i.icon-user
            %span#username-label

#messages

#modes-container{:class => 'tab-content'}
  #block-tab{:class => 'tab-pane active modes-tab-pane'}
    = render 'block_tab'

  #ruby-tab{:class => 'tab-pane modes-tab-pane'}
    #text-editor

= render 'signin_modal'
= render 'load_modal'
= render 'reset_modal'
= render 'preference_modal'

- if session[:username]
  :javascript
    window.Smalruby.username = '#{h session[:username]}';

:javascript
  window.Smalruby.Preferences = #{current_preferences.to_json};

Ruby216_32/lib/ruby/gems/2.1.0/gems/smalruby-editor-0.4.0-x86-mingw32/app/views/editor/toolbox.html.haml
= render "toolbox_#{toolbox_name}"